Fixed NoSuchMethodError for Jenkins Job for MBCC (#12618)
* Fixed NoSuchMethodError for Jenkins Job for MBCC

* Removed init_git since it's taken care of in unpack_and_init method