MXNet -> Apple CoreML converter (#7438)
* added coreml test converter for mxnet

* added prioritized todo items

* Updating parameters for 0.4.0 coreml.

This mainly required re-arranging the existing parameters.
The current test output looks like this:
====START=====
(coremltools) Pracheers-MacBook-Pro:core_ml pracheer$ python test_mxnet_converer.py
test_conv_random (__main__.MXNetSingleLayerTest) ... test_mxnet_converer.py:21: DeprecationWarning: mxnet.model.FeedForward has been deprecated. Please use mxnet.mod.Module instead.
  model = mx.model.FeedForward(net, engine, arg_params = engine.arg_dict)
3 : conv_1_output, Convolution
ok
test_flatten (__main__.MXNetSingleLayerTest) ... 3 : conv_1, Convolution
4 : flatten1, Flatten
7 : fc1, FullyConnected
9 : softmax_output, SoftmaxOutput
ok
test_really_tiny_2_inner_product_ones_input (__main__.MXNetSingleLayerTest) ... 3 : fc1_output, FullyConnected
ok
test_really_tiny_conv_random_3d_input (__main__.MXNetSingleLayerTest) ... 3 : conv_1_output, Convolution
ok
test_really_tiny_conv_random_input (__main__.MXNetSingleLayerTest) ... 3 : conv_1_output, Convolution
ok
test_really_tiny_conv_random_input_multi_filter (__main__.MXNetSingleLayerTest) ... 3 : conv_1_output, Convolution
ok
test_really_tiny_inner_product_ones_input (__main__.MXNetSingleLayerTest) ... 3 : fc1_output, FullyConnected
ok
test_tiny_asym_conv_random_asym_input (__main__.MXNetSingleLayerTest) ... 3 : conv_1, Convolution
4 : tanh_output, Activation
ok
test_tiny_asym_conv_random_input (__main__.MXNetSingleLayerTest) ... 3 : conv_1_output, Convolution
ok
test_tiny_conv_ones_input (__main__.MXNetSingleLayerTest) ... 3 : conv_1_output, Convolution
ok
test_tiny_conv_pooling_random_input (__main__.MXNetSingleLayerTest) ... 3 : conv_1, Convolution
4 : pool_1_output, Pooling
ok
test_tiny_conv_random_3d_input (__main__.MXNetSingleLayerTest) ... 3 : conv_1_output, Convolution
ok
test_tiny_conv_random_input (__main__.MXNetSingleLayerTest) ... 3 : conv_1_output, Convolution
ok
test_tiny_conv_random_input_multi_filter (__main__.MXNetSingleLayerTest) ... 3 : conv_1_output, Convolution
ok
test_tiny_inner_product_ones_input (__main__.MXNetSingleLayerTest) ... 3 : fc1_output, FullyConnected
ok
test_tiny_inner_product_random_input (__main__.MXNetSingleLayerTest) ... 3 : fc1_output, FullyConnected
ok
test_tiny_inner_product_zero_input (__main__.MXNetSingleLayerTest) ... 3 : fc1_output, FullyConnected
ok
test_tiny_relu_activation_random_input (__main__.MXNetSingleLayerTest) ... 3 : fc1, FullyConnected
4 : relu1_output, Activation
ok
test_tiny_sigmoid_activation_random_input (__main__.MXNetSingleLayerTest) ... 3 : fc1, FullyConnected
4 : sigmoid1_output, Activation
ok
test_tiny_softmax_random_input (__main__.MXNetSingleLayerTest) ... 3 : fc1, FullyConnected
5 : softmax_output, SoftmaxOutput
ok
test_tiny_tanh_activation_random_input (__main__.MXNetSingleLayerTest) ... 3 : fc1, FullyConnected
4 : tanh1_output, Activation
ok
test_transpose (__main__.MXNetSingleLayerTest) ... 1 : transpose, transpose
4 : conv_1_output, Convolution
ok

----------------------------------------------------------------------
Ran 22 tests in 2.167s

OK

====END=====

* Convert reshape operator into coreml equivalent.

* Set pre-processing parameters on coreml model.

* Adding synsets w/ unit test.

class_labels only used when coreml model is used in classifier mode so had to re-juggle few parameters to make it work.

* Minor documentation change for pre-processing args.

* Adding Deconvolution layer.

Currently target_shape has been compulsory since it is required by coreml. Also, we are not currently able to evaluate the affect of padding. If we try to xplicitly add padding to coreml model at the end we get an error. This is how we were adding the padding:
         pad = literal_eval(param['pad'])
         for i in range(len(pad)):
             convLayer.valid.paddingAmounts.borderAmounts[i].startEdgeSize = pad[i]
             convLayer.valid.paddingAmounts.borderAmounts[i].endEdgeSize = pad[i]

Error:
  File "test_mxnet_converer.py", line 22, in _get_coreml_model
    spec = mxnet_converter.convert(model, class_labels=class_labels, mode=mode, **input_shape)
  File "_mxnet_converter.py", line 197, in convert
    converter_func(net, node, model, builder)
  File "_layers.py", line 515, in convert_deconvolution
    convLayer.valid.paddingAmounts.borderAmounts[i].startEdgeSize = pad[i]
  File "/Users/pracheer/miniconda3/envs/coremltools/lib/python2.7/site-packages/google/protobuf/internal/containers.py", line 204, in __getitem__
    return self._values[key]
IndexError: list index out of range

Will fix the above two issues after discussions with coreml people.

* Skip dropout layer while converting.

* added quick todo

* Enable padding > 1 by adding an extra layer for padding in coreml.

Added unit tests.
Caveat: Currently deconv layer with padding !- (0, 0) is not working: Model successfully converts but mxnet predictions from coreml ones.

* Unit tests to convert entire model from zoo.

* fix module / BN

* refactor

* minor fix

* [BugFix] input-data as a dictionary.

In our previous commit, input-data was assumed as an array which caused unit tests to fail. This change fixes that. Also, add a missing parameter to couple of the tests in models-test.

* Use delta of 1e-3 instead of 1e-7 which was accidently pushed.

* Test inception_v3 and remove tests that do only conversion.

fwiw:On inception_v3, the predictions are off by more than delta.

* update converter unittests with mxnet module

* BatchNorm UnitTest+eps.

* add image classification test

* "Force" flag to force conversion of layers.

This is needed for layers which don't have an exact one-to-one correspondence in CoreML. By default, the conversion should fail if it detects that CoreML doesn't support the layer as it is but this behavior can be overriden if anyone provides force flag while calling convert.

Summary of changes:
- Add "force" flag to all the layers in _layers.
- For batchnorm conversion, don't throw the error if force flag is provided.
- 2 unit tests: one tests that an exception is thrown for converting batch-norm layer with local batch stats; other that tests that "force" flag causes it to not throw the exception.

* Minor: documentation fixes, fixing imports, etc.

* ModelsUnitTests: Improved documentation, using force flag where reqd, ability to download the model files if they don't exist.

* Minor: documentation update on KL divergence.

* Minor: Removing unused variables.

* Minor: documentation update for MXNetSingleLayerTest.

* test_image: add force flag for resnet.

* README; change name of classes; assert KLDivergence < 1e-4.

* Updated README.

* Minor: cosmetic changes to readme.

* convert return coreml instead of protobuf

* Minor: cosmetic changes to README.

* Enable SingleLayerTest.test_tiny_synset_random_input.

* Minor: fixing some formatting of README

* testing readme formatting

* Minor: Heading for TODOs in README.

* ImagenetTest: fix shapes, add more models.

* move test location, add mxnet_coreml_converter as Command Line Tool

* add mxnet random seed in converter unittest

* Updated README,fix vgg16 test, refactor deconv code.

* refactor directory and moving .mlmodel files

* Fixing README to have dimensions as 224.

* Adding periods at the end of sentences.

* Instead of commenting out a test, skip it.

* remove force flag, add preprocessing_args

* Updated README for pre-processing arguments.

* Deconv w/ padding; pooling w/ pooling_convention.

Earlier deconv w/ padding was giving incorrect predictions. We added crop layer which fixed the issues.
As for the pooling_convention, the current coremltools doesn't provide the support so we added our own custom implementation (w/ help from Apple) to overcome the issue.

* added coreml test converter for mxnet

* added prioritized todo items

* Updating parameters for 0.4.0 coreml.

This mainly required re-arranging the existing parameters.
The current test output looks like this:
====START=====
(coremltools) Pracheers-MacBook-Pro:core_ml pracheer$ python test_mxnet_converer.py
test_conv_random (__main__.MXNetSingleLayerTest) ... test_mxnet_converer.py:21: DeprecationWarning: mxnet.model.FeedForward has been deprecated. Please use mxnet.mod.Module instead.
  model = mx.model.FeedForward(net, engine, arg_params = engine.arg_dict)
3 : conv_1_output, Convolution
ok
test_flatten (__main__.MXNetSingleLayerTest) ... 3 : conv_1, Convolution
4 : flatten1, Flatten
7 : fc1, FullyConnected
9 : softmax_output, SoftmaxOutput
ok
test_really_tiny_2_inner_product_ones_input (__main__.MXNetSingleLayerTest) ... 3 : fc1_output, FullyConnected
ok
test_really_tiny_conv_random_3d_input (__main__.MXNetSingleLayerTest) ... 3 : conv_1_output, Convolution
ok
test_really_tiny_conv_random_input (__main__.MXNetSingleLayerTest) ... 3 : conv_1_output, Convolution
ok
test_really_tiny_conv_random_input_multi_filter (__main__.MXNetSingleLayerTest) ... 3 : conv_1_output, Convolution
ok
test_really_tiny_inner_product_ones_input (__main__.MXNetSingleLayerTest) ... 3 : fc1_output, FullyConnected
ok
test_tiny_asym_conv_random_asym_input (__main__.MXNetSingleLayerTest) ... 3 : conv_1, Convolution
4 : tanh_output, Activation
ok
test_tiny_asym_conv_random_input (__main__.MXNetSingleLayerTest) ... 3 : conv_1_output, Convolution
ok
test_tiny_conv_ones_input (__main__.MXNetSingleLayerTest) ... 3 : conv_1_output, Convolution
ok
test_tiny_conv_pooling_random_input (__main__.MXNetSingleLayerTest) ... 3 : conv_1, Convolution
4 : pool_1_output, Pooling
ok
test_tiny_conv_random_3d_input (__main__.MXNetSingleLayerTest) ... 3 : conv_1_output, Convolution
ok
test_tiny_conv_random_input (__main__.MXNetSingleLayerTest) ... 3 : conv_1_output, Convolution
ok
test_tiny_conv_random_input_multi_filter (__main__.MXNetSingleLayerTest) ... 3 : conv_1_output, Convolution
ok
test_tiny_inner_product_ones_input (__main__.MXNetSingleLayerTest) ... 3 : fc1_output, FullyConnected
ok
test_tiny_inner_product_random_input (__main__.MXNetSingleLayerTest) ... 3 : fc1_output, FullyConnected
ok
test_tiny_inner_product_zero_input (__main__.MXNetSingleLayerTest) ... 3 : fc1_output, FullyConnected
ok
test_tiny_relu_activation_random_input (__main__.MXNetSingleLayerTest) ... 3 : fc1, FullyConnected
4 : relu1_output, Activation
ok
test_tiny_sigmoid_activation_random_input (__main__.MXNetSingleLayerTest) ... 3 : fc1, FullyConnected
4 : sigmoid1_output, Activation
ok
test_tiny_softmax_random_input (__main__.MXNetSingleLayerTest) ... 3 : fc1, FullyConnected
5 : softmax_output, SoftmaxOutput
ok
test_tiny_tanh_activation_random_input (__main__.MXNetSingleLayerTest) ... 3 : fc1, FullyConnected
4 : tanh1_output, Activation
ok
test_transpose (__main__.MXNetSingleLayerTest) ... 1 : transpose, transpose
4 : conv_1_output, Convolution
ok

----------------------------------------------------------------------
Ran 22 tests in 2.167s

OK

====END=====

* Convert reshape operator into coreml equivalent.

* Adding Deconvolution layer.

Currently target_shape has been compulsory since it is required by coreml. Also, we are not currently able to evaluate the affect of padding. If we try to xplicitly add padding to coreml model at the end we get an error. This is how we were adding the padding:
         pad = literal_eval(param['pad'])
         for i in range(len(pad)):
             convLayer.valid.paddingAmounts.borderAmounts[i].startEdgeSize = pad[i]
             convLayer.valid.paddingAmounts.borderAmounts[i].endEdgeSize = pad[i]

Error:
  File "test_mxnet_converer.py", line 22, in _get_coreml_model
    spec = mxnet_converter.convert(model, class_labels=class_labels, mode=mode, **input_shape)
  File "_mxnet_converter.py", line 197, in convert
    converter_func(net, node, model, builder)
  File "_layers.py", line 515, in convert_deconvolution
    convLayer.valid.paddingAmounts.borderAmounts[i].startEdgeSize = pad[i]
  File "/Users/pracheer/miniconda3/envs/coremltools/lib/python2.7/site-packages/google/protobuf/internal/containers.py", line 204, in __getitem__
    return self._values[key]
IndexError: list index out of range

Will fix the above two issues after discussions with coreml people.

* Adding synsets w/ unit test.

class_labels only used when coreml model is used in classifier mode so had to re-juggle few parameters to make it work.

* Set pre-processing parameters on coreml model.

* Minor documentation change for pre-processing args.

* Skip dropout layer while converting.

* added quick todo

* Enable padding > 1 by adding an extra layer for padding in coreml.

Added unit tests.
Caveat: Currently deconv layer with padding !- (0, 0) is not working: Model successfully converts but mxnet predictions from coreml ones.

* Unit tests to convert entire model from zoo.

* fix module / BN

* refactor

* minor fix

* [BugFix] input-data as a dictionary.

In our previous commit, input-data was assumed as an array which caused unit tests to fail. This change fixes that. Also, add a missing parameter to couple of the tests in models-test.

* Use delta of 1e-3 instead of 1e-7 which was accidently pushed.

* Test inception_v3 and remove tests that do only conversion.

fwiw:On inception_v3, the predictions are off by more than delta.

* update converter unittests with mxnet module

* BatchNorm UnitTest+eps.

* add image classification test

* "Force" flag to force conversion of layers.

This is needed for layers which don't have an exact one-to-one correspondence in CoreML. By default, the conversion should fail if it detects that CoreML doesn't support the layer as it is but this behavior can be overriden if anyone provides force flag while calling convert.

Summary of changes:
- Add "force" flag to all the layers in _layers.
- For batchnorm conversion, don't throw the error if force flag is provided.
- 2 unit tests: one tests that an exception is thrown for converting batch-norm layer with local batch stats; other that tests that "force" flag causes it to not throw the exception.

* Minor: documentation fixes, fixing imports, etc.

* ModelsUnitTests: Improved documentation, using force flag where reqd, ability to download the model files if they don't exist.

* Minor: documentation update on KL divergence.

* Minor: Removing unused variables.

* Minor: documentation update for MXNetSingleLayerTest.

* test_image: add force flag for resnet.

* README; change name of classes; assert KLDivergence < 1e-4.

* Updated README.

* Minor: cosmetic changes to readme.

* convert return coreml instead of protobuf

* Minor: cosmetic changes to README.

* Enable SingleLayerTest.test_tiny_synset_random_input.

* Minor: fixing some formatting of README

* testing readme formatting

* Minor: Heading for TODOs in README.

* ImagenetTest: fix shapes, add more models.

* move test location, add mxnet_coreml_converter as Command Line Tool

* add mxnet random seed in converter unittest

* Updated README,fix vgg16 test, refactor deconv code.

* refactor directory and moving .mlmodel files

* Fixing README to have dimensions as 224.

* Adding periods at the end of sentences.

* Instead of commenting out a test, skip it.

* remove force flag, add preprocessing_args

* Updated README for pre-processing arguments.

* Deconv w/ padding; pooling w/ pooling_convention.

Earlier deconv w/ padding was giving incorrect predictions. We added crop layer which fixed the issues.
As for the pooling_convention, the current coremltools doesn't provide the support so we added our own custom implementation (w/ help from Apple) to overcome the issue.

* Moving files from core_ml directory to coreml directory since Apple guys pushed their code to coreml and we don't want to lose their history.

* Moved Apple files from core_ml to coreml directory since Apple pushed their code changes to coreml and we don't want to lose their history.

This change also add Apache license to all the files.

* Updated documentation for utils.py.

* Fixing Batchnorm test with the right delta.

* Updating README with information about mode/pre-processing-args/class-labels.