Fixed caffe_converter and improved test_converter (#6489)
* added support for running test_converter on cpu

* Added a missing check before searching for the bias blob name.
This prevents failure when converting the standard bvlc_googlenet model from the caffe model zoo.

* accuracy drop allowed should be 3% not 30%!

* fixed crash when converting resnet: rescale_factor = 1 / rescale_factor
TypeError: unsupported operand type(s) for /: 'int' and 'google.protobuf.pyext._message.RepeatedScalarContainer'

* fix lint issues: missing docstring and condition